server:
  port: 8690

product.host: http://localhost:8688
customer.host: http://localhost:8689

spring:
  cloud:
    aws:
      endpoint: http://localhost:4566

aws:
  sns:
    close-cart:
      name: local-cart-closed-topic