version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "P@55W0rD"
    ports:
      - "3366:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/script:/opt/scripts
      - ./docker/mysql/script/setup-product.sql:/docker-entrypoint-initdb.d/1.sql
      - ./docker/mysql/script/setup-customer.sql:/docker-entrypoint-initdb.d/2.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - tech-challenge-network-local

  redis:
    container_name: redis
    image: library/redis:6-alpine
    platform: linux/amd64
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6379", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - tech-challenge-network-local

  cdn:
    container_name: cdn
    image: nginx:alpine
    platform: linux/amd64
    restart: always
    ports:
      - "8888:8080"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost/monitor/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/static:/tech-challenge/static
    networks:
      - tech-challenge-network-local

  customer:
    container_name: customer
    image: fiapsoat2grupo13/customer-service:latest
    platform: linux/amd64
    ports:
      - "8689:8080"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost/monitor/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      "spring.profiles.active": "prod"
      "db.host": "mysql"
      "db.schema": "customer"
      "db.username": "sys_customer"
      "db.password": "customer_6#233zJMNTjkQb#sgps#"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tech-challenge-network-local

  product:
    container_name: product
    image: fiapsoat2grupo13/product-service:latest
    platform: linux/amd64
    ports:
      - "8688:8080"
    environment:
      "spring.profiles.active": "prod"
      "db.host": "mysql"
      "db.schema": "product"
      "db.username": "sys_product"
      "db.password": "product_6#233zJMNTjkQb#sgps#"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tech-challenge-network-local

  localstack:
    container_name: localstack
    image: fiapsoat2grupo13/localstack-resources:latest
    platform: linux/amd64
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - tech-challenge-network-local

networks:
  tech-challenge-network-local:
    driver: bridge
